services:
  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: server
    hostname: server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_KUBECONFIG_OUTPUT=/output/config
    - K3S_KUBECONFIG_MODE=666
    - K3S_SERVER_ARGS=--tls-san server
    volumes:
    - ./tmp:/output

  kubectl:
    build: .
    volumes:
    - ./tmp:/root/.kube
    environment:
    - KUBECONFIG=/root/.kube/config
    depends_on:
    - server
    networks:
    - default  # 同じネットワーク内で通信できるように

networks:
  default:
    driver: bridge

